In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df1 = pd.read_csv('all_songs_data_50k.csv')
df2 = pd.read_csv('validation_dataset.csv')

In [7]:
df = pd.concat([df1, df2], ignore_index=True)
df

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
0,6853b58d17e1fe68eff7d1bf,mark,"Hi, uhm, yeah, everytime na tingnan ko yung re...",2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-19T07:00:29.319655884Z
1,6853b58717e1fe68eff7d1be,dimas ali,I don't know if you still care about me or not...,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z
2,6853b58417e1fe68eff7d1bd,2229,"I'll always love you from this day on, now and...",37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z
3,6853b56717e1fe68eff7d1bc,savira ramadhani m,.,6GCW5Muk3u0cM5QTkS4C9a,The One That Got Away,Katy Perry,https://i.scdn.co/image/ab67616d0000b27343219f...,2025-06-19T06:59:51.325948562Z
4,6853b56617e1fe68eff7d1bb,drix,"hi drix, i hope when out paths met again, sana...",4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z
...,...,...,...,...,...,...,...,...
53534,68138f211fc54584f668c3bf,ayu,hey! i've seen u once sa morato playing billia...,6cEguiQecbXrFlsnMi2ysr,Come and See Me (feat. Drake),"PARTYNEXTDOOR, Drake",https://i.scdn.co/image/ab67616d0000b273240b49...,2025-05-01T15:11:29.050072684Z
53535,6812cf9b1fc54584f668a368,ayu,untuk seseorang di bawah yg menggunakan lagu i...,57RA3JGafJm5zRtKJiKPIm,Are You Bored Yet? (feat. Clairo),"Wallows, Clairo",https://i.scdn.co/image/ab67616d0000b27384feca...,2025-05-01T01:34:19.555554536Z
53536,680bd9c01fc54584f6678c2e,ayu,disappointed. thanks a lot,0bht8SpPHXiUMApKcua4Mz,Take Care,NIKI,https://i.scdn.co/image/ab67616d0000b2734d3d39...,2025-04-25T18:51:44.276404573Z
53537,680b59f31fc54584f6676859,ayu,jujur aja guel sedih liat org yang gue cintai ...,1tqPw8Hf88h24Bpt2SzuYE,Di Akhir Perang,Nadin Amizah,https://i.scdn.co/image/ab67616d0000b273948476...,2025-04-25T09:46:27.779280549Z
53538,6809e4571fc54584f666ffca,ayu,haloo kak aku al ini buat ka ayu di serang aku...,55dLT3WApUJBEWxSJSivyt,"I Love You, I'm Sorry - Live From Vevo",Gracie Abrams,https://i.scdn.co/image/ab67616d0000b273e5ff16...,2025-04-24T07:12:23.706454691Z

In [9]:
df = df.drop_duplicates(subset=['_id'], keep='first')
df

,_id,recipient,message,song_id,song_name,song_artist,song_image,created_at
0,6853b58d17e1fe68eff7d1bf,mark,"Hi, uhm, yeah, everytime na tingnan ko yung re...",2U3jOPfO4wZZFaaWS4Dcj6,stranger,Olivia Rodrigo,https://i.scdn.co/image/ab67616d0000b2734063d6...,2025-06-19T07:00:29.319655884Z
1,6853b58717e1fe68eff7d1be,dimas ali,I don't know if you still care about me or not...,6BQPRUFGHsgtNYJxuwhktR,This Is How It Feels (with Laufey),"d4vd, Laufey",https://i.scdn.co/image/ab67616d0000b27364fa1b...,2025-06-19T07:00:23.212049427Z
2,6853b58417e1fe68eff7d1bd,2229,"I'll always love you from this day on, now and...",37mbA1RwYja7WFaIOzSczX,You'll Be In My Heart - Spotify Singles,NIKI,https://i.scdn.co/image/ab67616d0000b273e68520...,2025-06-19T07:00:20.622764007Z
3,6853b56717e1fe68eff7d1bc,savira ramadhani m,.,6GCW5Muk3u0cM5QTkS4C9a,The One That Got Away,Katy Perry,https://i.scdn.co/image/ab67616d0000b27343219f...,2025-06-19T06:59:51.325948562Z
4,6853b56617e1fe68eff7d1bb,drix,"hi drix, i hope when out paths met again, sana...",4cBm8rv2B5BJWU2pDaHVbF,Multo,Cup of Joe,https://i.scdn.co/image/ab67616d0000b273394048...,2025-06-19T06:59:50.396334841Z
...,...,...,...,...,...,...,...,...
53534,68138f211fc54584f668c3bf,ayu,hey! i've seen u once sa morato playing billia...,6cEguiQecbXrFlsnMi2ysr,Come and See Me (feat. Drake),"PARTYNEXTDOOR, Drake",https://i.scdn.co/image/ab67616d0000b273240b49...,2025-05-01T15:11:29.050072684Z
53535,6812cf9b1fc54584f668a368,ayu,untuk seseorang di bawah yg menggunakan lagu i...,57RA3JGafJm5zRtKJiKPIm,Are You Bored Yet? (feat. Clairo),"Wallows, Clairo",https://i.scdn.co/image/ab67616d0000b27384feca...,2025-05-01T01:34:19.555554536Z
53536,680bd9c01fc54584f6678c2e,ayu,disappointed. thanks a lot,0bht8SpPHXiUMApKcua4Mz,Take Care,NIKI,https://i.scdn.co/image/ab67616d0000b2734d3d39...,2025-04-25T18:51:44.276404573Z
53537,680b59f31fc54584f6676859,ayu,jujur aja guel sedih liat org yang gue cintai ...,1tqPw8Hf88h24Bpt2SzuYE,Di Akhir Perang,Nadin Amizah,https://i.scdn.co/image/ab67616d0000b273948476...,2025-04-25T09:46:27.779280549Z
53538,6809e4571fc54584f666ffca,ayu,haloo kak aku al ini buat ka ayu di serang aku...,55dLT3WApUJBEWxSJSivyt,"I Love You, I'm Sorry - Live From Vevo",Gracie Abrams,https://i.scdn.co/image/ab67616d0000b273e5ff16...,2025-04-24T07:12:23.706454691Z